const plunderCardsData = {
  name: "plunder",
  cards: [
    {
      id: 0,
      name: "JewelledEgg",
      type: ["Treasure"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 1,
      name: "Search",
      type: ["Action", "Duration"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 2,
      name: "Pickaxe",
      type: ["Treasure"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 3,
      name: "WealthyVillage",
      type: ["Action"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 4,
      name: "SackofLoot",
      type: ["Treasure"],
      cost: {
        coin: 6,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 5,
      name: "Cutthroat",
      type: ["Action", "Duration", "Attack"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },

    {
      id: 6,
      name: "Bury",
      type: ["Event"],
      cost: {
        coin: 1,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 7,
      name: "Avoid",
      type: ["Event"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 8,
      name: "Deliver",
      type: ["Event"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 9,
      name: "Peril",
      type: ["Event"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 10,
      name: "Rush",
      type: ["Event"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 11,
      name: "Foray",
      type: ["Event"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 12,
      name: "Launch",
      type: ["Event"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 13,
      name: "Mirror",
      type: ["Event"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 14,
      name: "Prepare",
      type: ["Event"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 15,
      name: "Scrounge",
      type: ["Event"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 16,
      name: "Journey",
      type: ["Event"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 17,
      name: "Maelstrom",
      type: ["Event"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 18,
      name: "Looting",
      type: ["Event"],
      cost: {
        coin: 6,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 19,
      name: "Invasion",
      type: ["Event"],
      cost: {
        coin: 10,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 20,
      name: "Prosper",
      type: ["Event"],
      cost: {
        coin: 10,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },

    {
      id: 21,
      name: "Cage",
      type: ["Treasure", "Duration"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 22,
      name: "Grotto",
      type: ["Action", "Duration"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 23,
      name: "Search",
      type: ["Action", "Duration"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 24,
      name: "Shaman",
      type: ["Action"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 25,
      name: "SecludedShrine",
      type: ["Action", "Duration"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 26,
      name: "Siren",
      type: ["Action", "Duration", "Attack"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 27,
      name: "Stowaway",
      type: ["Action", "Duration", "Reaction"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 28,
      name: "Taskmaster",
      type: ["Action", "Duration"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 29,
      name: "Abundance",
      type: ["Treasure", "Duration"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 30,
      name: "CabinBoy",
      type: ["Action", "Duration"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 31,
      name: "Crucible",
      type: ["Treasure"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 32,
      name: "Flagship",
      type: ["Action", "Duration", "Command"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 33,
      name: "FortuneHunter",
      type: ["Action"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 34,
      name: "Gondola",
      type: ["Treasure", "Duration"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 35,
      name: "HarborVillage",
      type: ["Action"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 36,
      name: "LandingParty",
      type: ["Action", "Duration"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 37,
      name: "Mapmaker",
      type: ["Action", "Reaction"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 38,
      name: "Maroon",
      type: ["Action"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 39,
      name: "Rope",
      type: ["Treasure", "Duration"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 40,
      name: "SwampShacks",
      type: ["Action"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 41,
      name: "Tools",
      type: ["Treasure"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 42,
      name: "BuriedTreasure",
      type: ["Treasure", "Duration"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 43,
      name: "Crew",
      type: ["Action", "Duration"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 44,
      name: "Enlarge",
      type: ["Action", "Duration"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 45,
      name: "Figurine",
      type: ["Treasure"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 46,
      name: "FirstMate",
      type: ["Action"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 47,
      name: "Frigate",
      type: ["Action", "Duration", "Attack"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 48,
      name: "Longship",
      type: ["Action", "Duration"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 49,
      name: "MiningRoad",
      type: ["Action"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 50,
      name: "Pendant",
      type: ["Treasure"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 51,
      name: "Pilgrim",
      type: ["Action"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 52,
      name: "Quartermaster",
      type: ["Action", "Duration"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 53,
      name: "SilverMine",
      type: ["Treasure"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 54,
      name: "Trickster",
      type: ["Action", "Attack"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 55,
      name: "KingsCache",
      type: ["Treasure"],
      cost: {
        coin: 7,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },

    {
      id: 56,
      name: "Cheap",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 57,
      name: "Cursed",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 58,
      name: "Fated",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 59,
      name: "Fawning",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 60,
      name: "Friendly",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 61,
      name: "Hasty",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 62,
      name: "Inherited",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 63,
      name: "Inspiring",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 64,
      name: "Nearby",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 65,
      name: "Patient",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 66,
      name: "Pious",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 67,
      name: "Reckless",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 68,
      name: "Rich",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 69,
      name: "Shy",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 70,
      name: "Tireless",
      type: ["Trait"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
  ],
};

export default plunderCardsData;
