export const risingSunCardsData = {
  name: "rising_sun",
  cards: [
    {
      id: 0,
      name: "Alley",
      type: ["Action", "Shadow"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 1,
      name: "Aristocrat",
      type: ["Action"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 2,
      name: "Artist",
      type: ["Action"],
      cost: {
        coin: 0,
        debt: 8,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 3,
      name: "Change",
      type: ["Action"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 4,
      name: "CraftsMan",
      type: ["Action"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 5,
      name: "Daimyo",
      type: ["Action", "Command"],
      cost: {
        coin: 0,
        debt: 6,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 6,
      name: "Fishmonger",
      type: ["Action", "Shadow"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 7,
      name: "GoldMine",
      type: ["Action"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 8,
      name: "ImperialEnvoy",
      type: ["Action"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 9,
      name: "Kitsune",
      type: ["Action", "Attack", "Omen"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 10,
      name: "Litter",
      type: ["Action"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 11,
      name: "MountainShrine",
      type: ["Action", "Omen"],
      cost: {
        coin: 0,
        debt: 5,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 12,
      name: "Ninja",
      type: ["Action", "Attack", "Shadow"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 13,
      name: "Poet",
      type: ["Action", "Omen"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 14,
      name: "Rice",
      type: ["Treasure"],
      cost: {
        coin: 7,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 15,
      name: "RiceBroker",
      type: ["Action"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 16,
      name: "RiverShrine",
      type: ["Action", "Omen"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 17,
      name: "RiverBoat",
      type: ["Action", "Duration"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 18,
      name: "Ronin",
      type: ["Action", "Shadow"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 19,
      name: "RootCellar",
      type: ["Action"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 20,
      name: "RusticVillage",
      type: ["Action", "Omen"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 21,
      name: "Samurai",
      type: ["Action", "Duration", "Attack"],
      cost: {
        coin: 6,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 22,
      name: "SnakeWitch",
      type: ["Action", "Attack"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 23,
      name: "Tanuki",
      type: ["Action", "Shadow"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 24,
      name: "TeaHouse",
      type: ["Action", "Omen"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 10,
      isKingdom: true,
      specialNotes: "",
    },
    {
      id: 25,
      name: "Continue",
      type: ["Event"],
      cost: {
        coin: 0,
        debt: 8,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 26,
      name: "Amass",
      type: ["Event"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 27,
      name: "Asceticism",
      type: ["Event"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 28,
      name: "Credit",
      type: ["Event"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 29,
      name: "Foresight",
      type: ["Event"],
      cost: {
        coin: 2,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 30,
      name: "Kintsugi",
      type: ["Event"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 31,
      name: "Practice",
      type: ["Event"],
      cost: {
        coin: 3,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 32,
      name: "SeaTrade",
      type: ["Event"],
      cost: {
        coin: 4,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 33,
      name: "ReceiveTribute",
      type: ["Event"],
      cost: {
        coin: 5,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 34,
      name: "Gather",
      type: ["Event"],
      cost: {
        coin: 7,
        debt: 0,
      },
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 35,
      name: "ApproachingArmy",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 36,
      name: "BidingTime",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 37,
      name: "Bureaucracy",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 38,
      name: "DivineWind",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 39,
      name: "Enlightenment",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 40,
      name: "FlourishingTrade",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 41,
      name: "GoodHarvest",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 42,
      name: "GreatLeader",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 43,
      name: "Growth",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 44,
      name: "HarshWinter",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 45,
      name: "KindEmperor",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 46,
      name: "Panic",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 47,
      name: "Progress",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 48,
      name: "RapidExpansion",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
    {
      id: 49,
      name: "Sickness",
      type: ["Prophecy"],
      cost: {},
      initAmount: 1,
      isKingdom: false,
      specialNotes: "",
    },
  ],
};
